version: '3'

services:
  backend:
    image: registry.gitlab.propulsion-home.ch/greasy-namsi/motion-project-greasy:latest
    restart: on-failure
    env_file:
      - ./envs/dev.env
    command: 'sh /scripts/dev.sh'
    depends_on:
      - postgres

    volumes:
      - ./backend:/backend
      - media-files:/media-files
      - static-files:/static-files
    ports:
      - '8000:8000'

  postgres:
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./envs/dev.env
    ports:
      - "5432:5432"

volumes:
  media-files:
  static-files:
  postgres: