name: backend
dependencies:
  - python=3.8
  - psycopg2
  - pip
  - pip:
      - asgiref==3.2.10
      - certifi==2020.6.20
      - Django==3.1.2
      - djangorestframework==3.12.1
      - djangorestframework-simplejwt==4.4.0
      - PyJWT==1.7.1
      - pytz==2020.1
      - sqlparse==0.4.1
      - wincertstore==0.2
      - pillow==7.2.0
      - gunicorn
      - flake8
      - django-filter==2.4.0
      - django-cors-headers==3.5.0

