# Generated by Django 3.1.2 on 2020-10-21 10:18

import apps.register.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.register.models.code_generator, max_length=6, unique=True)),
                ('code_used', models.BooleanField(default=False)),
            ],
        ),
    ]
